#!/bin/sh -e

DEB_HOST_MULTIARCH=__DEB_HOST_MULTIARCH__

SONAME=__PETSC_SONAME_VERSION__

PETSC_VERSION=__PETSC_VERSION__
PETSC_ARCH=${DEB_HOST_MULTIARCH}
PETSC_REAL_ARCH=${PETSC_ARCH}-real
PETSC_SONAME_VERSION=__PETSC_SONAME_VERSION__
PETSC_NAME=petsc${PETSC_SONAME_VERSION}

PETSC_DIR_REAL=/usr/lib/petscdir/${PETSC_NAME}/${PETSC_REAL_ARCH}

# Remove alternatives links
if [ "$1" = "remove" ]; then
  update-alternatives --remove petsc ${PETSC_DIR_REAL}
  update-alternatives --remove libpetsc_real.so /usr/lib/${DEB_HOST_MULTIARCH}/libpetsc_real.so.${PETSC_VERSION}

  # remove general X.Y soname alternatives
  update-alternatives --remove petsc${SONAME} ${PETSC_DIR_REAL}

fi

#DEBHELPER#
