#!/bin/sh -e

DEB_HOST_MULTIARCH=__DEB_HOST_MULTIARCH__

SONAME=__PETSC_SONAME_VERSION__

PETSC_VERSION=__PETSC_VERSION__
PETSC_ARCH=${DEB_HOST_MULTIARCH}
PETSC_COMPLEX_ARCH=${PETSC_ARCH}-complex
PETSC_VERSION_NUMBER=$( echo ${PETSC_VERSION} | sed "s/\.//g" )
PETSC_SONAME_VERSION=__PETSC_SONAME_VERSION__
PETSC_NAME=petsc${PETSC_SONAME_VERSION}

PETSC_DIR_COMPLEX=/usr/lib/petscdir/${PETSC_NAME}/${PETSC_COMPLEX_ARCH}

# Make alternatives links
if [ "$1" = "configure" ]; then

# alternative libpetsc.so.multiarch is deprecated
# test if libpetsc.so.multiarch is still in use
if update-alternatives --query petsc | grep libpetsc.so.multiarch > /dev/null ; then
  # if so, refresh the alternatives (remove libpetsc.so.multiarch) by removing the old definitions
  # Show no mercy. Wipe them out. All of them..
  # i.e. remove both real and complex alternatives for the old version
  # This should be safe since Conflicts are set up with the package versions using deprecated libpetsc.so.multiarch.
  echo Removing deprecated petsc alternatives using libpetsc.so.multiarch.
  for alt in `update-alternatives --list petsc`; do
    update-alternatives --remove petsc ${alt}
  done
fi


# alternative default petsc (e.g. real or complex)
update-alternatives --install /usr/lib/petsc petsc ${PETSC_DIR_COMPLEX} ${PETSC_VERSION_NUMBER}77 \
  --slave /usr/lib/${DEB_HOST_MULTIARCH}/libpetsc.so libpetsc.so /usr/lib/${DEB_HOST_MULTIARCH}/libpetsc_complex.so.${PETSC_VERSION} \
  --slave /usr/include/petsc petscinclude ${PETSC_DIR_COMPLEX}/include \
  --slave /usr/lib/${DEB_HOST_MULTIARCH}/pkgconfig/PETSc.pc PETSc.pc ${PETSC_DIR_COMPLEX}/lib/pkgconfig/PETSc.pc \
  --slave /usr/lib/${DEB_HOST_MULTIARCH}/pkgconfig/petsc.pc petsc.pc ${PETSC_DIR_COMPLEX}/lib/pkgconfig/petsc.pc \
  --slave /usr/share/octave/site/m/petsc petsc-octave ${PETSC_DIR_COMPLEX}/share/petsc/matlab

# alternative base version of petsc complex
update-alternatives --install /usr/lib/${DEB_HOST_MULTIARCH}/libpetsc_complex.so libpetsc_complex.so /usr/lib/${DEB_HOST_MULTIARCH}/libpetsc_complex.so.${PETSC_VERSION} ${PETSC_VERSION_NUMBER}73 \
 --slave /usr/lib/petscdir/petsc-complex petsc-complex ${PETSC_DIR_COMPLEX}

# alternative petsc for this X.Y soname (e.g. real or complex)
update-alternatives --install /usr/lib/petscdir/${SONAME} petsc${SONAME} ${PETSC_DIR_COMPLEX} ${PETSC_VERSION_NUMBER}73

fi


#DEBHELPER#
